#include "attachment/implementation.cpp"

#include "config/config.cpp"
#include "error/error_code.cpp"
#include "error/exception.cpp"
#include "error/translate_error.cpp"
#include "events/implementation.cpp"
#include "keyboard/layout.cpp"
#include "long_poll/long_poll.cpp"
#include "methods/basic.cpp"
#include "methods/constructor.cpp"
#include "methods/message_constructor.cpp"
#include "oauth/client.cpp"
