#include "attachment/implementation.cpp"

#include "config/config.cpp"
#include "events/implementation.cpp"
#include "exception/error_code.cpp"
#include "exception/exception.cpp"
#include "exception/translate_error.cpp"
#include "keyboard/layout.cpp"
#include "long_poll/long_poll.cpp"
#include "methods/basic.cpp"
#include "methods/utility/constructor.cpp"
#include "methods/utility/message_constructor.cpp"
#include "oauth/client.cpp"
