include_directories(modules/spdlog/include)
include_directories(cpp_vk_lib)
include_directories(modules/asio/asio/include)
add_executable(long_poll_example test/long_poll/long_poll.cpp)
target_link_libraries(long_poll_example cpp_vk_lib)
