#include "vk/src/attachment/audio.cpp"
#include "vk/src/attachment/audio_message.cpp"
#include "vk/src/attachment/base.cpp"
#include "vk/src/attachment/document.cpp"
#include "vk/src/attachment/photo.cpp"
#include "vk/src/attachment/video.cpp"
#include "vk/src/attachment/wall.cpp"